### ISSUE TITLE
[Feature Request] PDF support

### ISSUE THREAD

**Issue by certified-person** [corollari/waspline-reader#4]
The main thing I'd love to use Waspline for is to assist in reading PDFs (I read a lot of research articles, Waspline would definitely make that go faster!). I realise this would likely be a very big job to do, I just wanted to suggest it as a feature in case that's something you might look into doing. 

I appreciate your work, and the existence of Waspline!!

**Comment by corollari** [comment]
Hey @certified-person in the past I looked into implementing that by forking pdf.js (the pdf viewer used by firefox) and modifying it to add gradients to the lines.

After about 1 day of fiddling with it I didn't find any easy way to do that, partially because in some pdfs the characters printed on screen are encoded separately (eg: they just provide the x,y coordinates of the character) and this makes them harder to process compared to html pages.

So, while I believe this is entirely possible to achieve it requires pouring some time into it (increased by the fact that you also need to learn about the inner workings of pdf.js in order to modify it) which I currently don't have available, and probably won't have in the future, so this is not a feature I can work on personally.

That said, if you or somebody else is interested on working on that I would love to help with anything and any pull requests would be accepted after a quick review.

**Comment by corollari** [comment]
Closing as there's been no response and it's not something that will be implemented any time soon unless someone else prepares a PR.

**Comment by YaseenAlk** [comment]
Hey @corollari , nice extension! I might mess around and see if I can add some minimal pdf support on Chrome. Do you have some example PDFs that would be good for testing, e.g. the ones with different encodings that you mentioned in your previous comment. Thanks!
